version: "3.8"

services:

  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - users_api
    networks:
      - dev_network
  
  users_api:
    build:
      context: ./APIS
    deploy:
<<<<<<< HEAD
      replicas: 1  # Reducido para evitar conflictos
=======
      replicas: 1
>>>>>>> e68ea9d878d5ea7566755a8a3f2b289c1df87531
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "4000:4010"  # Cambia a un solo puerto, o usa puertos únicos por instancia
    volumes:
      - ./APIS/usuarios:/usr/userAPI
    networks:
      - dev_network

  db_dev:
<<<<<<< HEAD
    build:
      context: .
      dockerfile: Dockerfile.postgres_audit
=======
    image: postgres:17   # Usando la imagen oficial de PostgreSQL
>>>>>>> e68ea9d878d5ea7566755a8a3f2b289c1df87531
    container_name: users_db_dev
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 4GB
        reservations:
          cpus: "0.1"
          memory: 1GB
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: my_database
    volumes:
<<<<<<< HEAD
      - ./users_data_dev:/var/lib/postgresql/data
      - ./pg_logs:/var/log/postgresql
      - ./postgresql_configs/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql_configs/pg_hba.conf:/etc/postgresql/pg_hba.conf
=======
      - ./users_data_dev:/var/lib/postgresql/data  # Datos de PostgreSQL
      - ./users_logs:/var/log/postgresql           # Logs de PostgreSQL
      - ./postgresql_configs:/etc/postgresql       # Configuración de PostgreSQL
>>>>>>> e68ea9d878d5ea7566755a8a3f2b289c1df87531
    networks:
      - dev_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - 8888:80 
    environment:
      PGADMIN_DEFAULT_EMAIL: cafe@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
<<<<<<< HEAD

volumes:
  cafe_db_data:

=======
>>>>>>> e68ea9d878d5ea7566755a8a3f2b289c1df87531
